apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loadBalancer.name }}
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - protocol: {{ .Values.loadBalancer.protocol }}
      port: {{ .Values.loadBalancer.port }}
      targetPort: {{ .Values.loadBalancer.targetPort }}
  
