replicaCount: 2

deployment:
  name: petclinic-deployment

image:
  name: petclinic
  repository: bole1709/main
  pullPolicy: Always
  tag: actions
  containerPort: 8080

loadBalancer:
  name: petclinic-load-balancer
  type: LoadBalancer
  protocol: TCP
  port: 80
  targetPort: 8080
